<?php
namespace phpformsframework\libs\gui;

use phpformsframework\libs\cache\Buffer;
use phpformsframework\libs\Debug;
use phpformsframework\libs\storage\Filemanager;
use Exception;
use phpformsframework\libs\storage\Media;
use stdClass;

/**
 * Class Widget
 * @package phpformsframework\libs\gui
 */
abstract class Widget extends Controller
{
    private const VIEW_DEFAULT                      = "index";

    protected const ERROR_BUCKET                    = "widget";

    protected $requiredJs                           = [];
    protected $requiredCss                          = [];

    private $config                                 = [];
    private $resources                              = null;

    private $template                               = null;

    /**
     * Widget constructor.
     * @param array|null $config
     */
    public function __construct(array $config = null)
    {
        parent::__construct($config);

        $this->config                               = $config ?? [];
    }

    /**
     * Utility Builder
     * ------------------------------------------------------------------------
     */

    /**
     * @param string $filename_or_url
     * @param string|null $mode
     * @return string
     * @throws Exception
     */
    public function getImageUrl(string $filename_or_url, string $mode = null): string
    {
        $resources = $this->getResources();
        if (!empty($resources->images[$filename_or_url])) {
            return Media::getUrl($resources->images[$filename_or_url], $mode);
        }

        return  parent::getImageUrl($filename_or_url, $mode);
    }

    /**
     * Assets Method
     * ------------------------------------------------------------------------
     */

    /**
     * @param string $filename_or_url
     * @param string|null $device
     * @param string|null $media_query
     * @return Controller
     * @throws Exception
     */
    protected function addStylesheet(string $filename_or_url, string $device = null, string $media_query = null) : Controller
    {
        $resources = $this->getResources();
        if (!empty($resources->css[$filename_or_url])) {
            $filename_or_url = $resources->css[$filename_or_url];
        }

        return parent::addStylesheet($filename_or_url, $device, $media_query);
    }

    /**
     * @param string $filename_or_url
     * @param string|null $device
     * @param string|null $media_query
     * @return Controller
     * @throws Exception
     */
    protected function addFont(string $filename_or_url, string $device = null, string $media_query = null) : Controller
    {
        $resources = $this->getResources();
        if (!empty($resources->font[$filename_or_url])) {
            $filename_or_url = $resources->font[$filename_or_url];
        }

        return parent::addFont($filename_or_url, $device, $media_query);
    }


    protected function addJavascript(string $filename_or_url, string $location = null): Controller
    {
        $resources = $this->getResources();
        if (!empty($resources->js[$filename_or_url])) {
            $filename_or_url = $resources->js[$filename_or_url];
        }

        return parent::addJavascript($filename_or_url, $location); // TODO: Change the autogenerated stub
    }
    /**
     * Standard Method
     * ------------------------------------------------------------------------
     */


    /**
     * @param string|null $template_name
     * @param string|null $theme_name
     * @return View
     * @throws Exception
     */
    protected function view(string $template_name = null, string $theme_name = null) : View
    {
        if (!empty($this->view)) {
            return $this->view;
        }

        $this->template                             = $template_name ?? self::VIEW_DEFAULT;
        $resources                                  = $this->getResources();
        if (empty($resources->html[$this->template])) {
            throw new Exception("Template not found for Widget " . $this->class_name, 404);
        }

        return $this->view = (new View($this->config($resources->cfg[$this->template] ?? null)))->fetch($resources->html[$this->template]);
    }

    /**
     * @param string|null $template_name
     * @return object
     */
    protected function getConfig(string $template_name = null) : object
    {
        return json_decode(json_encode($this->config($this->getResources()->cfg[$template_name ?? self::VIEW_DEFAULT] ?? null)));
    }

    /**
     * @param string|null $file_path
     * @return array|null
     */
    private function config(string $file_path = null) : ?array
    {
        static $configs                             = null;

        if ($file_path && !isset($configs[$file_path])) {
            $configs[$file_path]                    = array_replace_recursive($this->loadConfig($file_path), $this->config);
        }

        return $configs[$file_path] ?? null;
    }

    /**
     * @return stdClass
     */
    private function getResources() : stdClass
    {
        if (!isset($this->resources[$this->class_name])) {
            $this->resources[$this->class_name]                 = Resource::widget($this->class_name);
        }

        return (object) ($this->resources[$this->class_name] ?? null);
    }

    /**
     * @throws Exception
     */
    protected function parseAssets() : void
    {
        $resources                                  = $this->getResources();
        $template                                   = $this->template;
        $this->parseRequiredAssets();

        if (!empty($resources->js[$template])) {
            $this->addJavascriptAsync($resources->js[$template]);
        }
        if (!empty($resources->css[$template])) {
            $this->addStylesheet($resources->css[$template]);
        }
    }

    /**
     * @throws Exception
     */
    private function parseRequiredAssets() : void
    {
        foreach ($this->requiredJs as $js) {
            $this->addJavascriptAsync($js);
        }
        foreach ($this->requiredCss as $css) {
            $this->addStylesheet($css);
        }
    }

    /**
     * @param string $file_path
     * @return array
     */
    private function loadConfig(string $file_path) : array
    {
        Debug::stopWatch(static::ERROR_BUCKET . "/map/" . $this->class_name);

        $cache                                      = Buffer::cache("widget");
        $config                                     = $cache->get($this->class_name);
        if (!$config) {
            $config                                 = Filemanager::getInstance("json")->read($file_path);

            $cache->set($this->class_name, $config, [$file_path => filemtime($file_path)]);
        }

        Debug::stopWatch(static::ERROR_BUCKET . "/map/". $this->class_name);

        return (array) $config;
    }
}
